# fly.toml app configuration file generated for mcdiscordbot on 2026-06-20T14:27:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mcdiscordbot"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

[[vm]]
  cpu_kind = 'shared'
  cpus = 8
  memory = '16gb'
  memory_mb = 16384
  processes = ['app']
  size = 'shared-cpu-8x'
