app = "mc-fly-bot"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  NODE_ENV = "production"

[processes]
  app = "node index.js"

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 8080
